
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Sep 24 15:47:01 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 41;
  public static final int INCREMENT = 17;
  public static final int CONST = 6;
  public static final int NOTEQUAL = 26;
  public static final int LPAREN = 37;
  public static final int GREATER = 27;
  public static final int SEMI = 34;
  public static final int CONTINUE = 15;
  public static final int REF = 35;
  public static final int MINUS = 22;
  public static final int DECREMENT = 18;
  public static final int RPAREN = 38;
  public static final int AND = 31;
  public static final int EQUALTO = 19;
  public static final int OR = 32;
  public static final int COMMA = 36;
  public static final int CLASS = 4;
  public static final int DIV = 24;
  public static final int LESSER = 29;
  public static final int PLUS = 21;
  public static final int IF = 7;
  public static final int FINDANY = 43;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 42;
  public static final int EQUAL = 33;
  public static final int LAMBDA = 20;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int NUMBER = 45;
  public static final int MOD = 25;
  public static final int IDENT = 46;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int FOREACH = 16;
  public static final int LESSEREQ = 30;
  public static final int LBRACE = 39;
  public static final int ELSE = 5;
  public static final int READ = 11;
  public static final int CHARCONST = 48;
  public static final int WHILE = 8;
  public static final int RBRACE = 40;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int GREATEREQ = 28;
  public static final int COUNT = 44;
  public static final int PRINT = 10;
}

